base:
  role: "validator"
  data_dir: "/tmp/node4/data"
  waypoint:
    from_file: "/tmp/node4/config/waypoint.txt"

consensus:
  safety_rules:
    backend:
      type: "on_disk_storage"
      path: /tmp/node4/data/secure_storage.json
    initial_safety_rules_config:
      from_file:
        waypoint:
          from_file: /tmp/node4/config/waypoint.txt
        identity_blob_path: /tmp/node4/config/validator-identity.yaml
  enable_pipeline: true

validator_network:
  network_id: validator
  listen_address: "/ip4/127.0.0.1/tcp/6180"
  discovery_method: 
    onchain
  mutual_authentication: true
  identity:
    type: "from_file"
    path: /tmp/node4/config/validator-identity.yaml

storage:
  dir: "/tmp/node4/data"

node_config_path: "/tmp/node4/config/nodes_config.json"

log_file_path: "/tmp/node4/consensus_log"

inspection_service:
  port: 10003
  address: 0.0.0.0

mempool:
  capacity_per_user: 20000
