[package]
name = "kvstore-v2"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
api.workspace = true
api-types.workspace = true
tokio.workspace = true
serde_json.workspace = true
serde.workspace = true
