[package]
name = "kvstore-v2"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
api.workspace = true
api-types.workspace = true
tokio.workspace = true
serde_json.workspace = true
serde.workspace = true
async-trait = { workspace = true }
clap = { version = "4.3.9", features = ["derive", "env", "unstable-styles"] }
clap-verbosity-flag = "2.1.1"
clap_complete = "4.4.1"
clap_derive = "4.5.18"
futures-channel = "0.3.29"
ruint = "1.12.3"
tokio-stream = "0.1.16"
rand = "0.8"
flexi_logger = "0.23"
log = "0.4"