[package]
name = "kvstore"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1.53"
api.workspace = true
api-types.workspace = true
rand = "0.8.5"
serde = { workspace = true }
serde_json = "1.0"
ethers = "2.0"
bincode = "1.3"
sha2 = "0.10"
leveldb = "0.8"
db-key = "0.0.5"
futures-channel = "0.3.29"
ruint = "1.12.3"
tokio = "1.40.0"
tokio-stream = "0.1.16"
clap = { version = "4.3.9", features = ["derive", "env", "unstable-styles"] }
clap-verbosity-flag = "2.1.1"
clap_complete = "4.4.1"
clap_derive = "4.5.18"
eyre = "0.6.12"
