[package]
name = "reth_v2"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true




[dependencies]
futures-util = "0.3.30"
clap = { version = "4.5.17", features = ["derive", "env"] }
futures = "0.3.30"
dirs = "5.0.1"
tokio = "1.40.0"
tokio-stream = "0.1.16"


eyre = "0.6.12"
tracing = "0.1.40"
tempfile = "3.12.0"
api.workspace = true
api-types.workspace = true
jsonrpsee = "=0.24.4"
hex = "0.4.3"
serde_json = "1.0.128"
bincode = "1.3"
time = "0.3.36"
anyhow = "1.0.87"
alloy = {version =  "0.3.6", features = ["eip712", "consensus", "rlp", "eips"] }
revm = { version = "=14.0.2" }
revm-inspectors = {version = "=0.7"}
revm-primitives = { version = "=9.0.2", features = [
    "std",
], default-features = false }
alloy-chains = "=0.1.32"
alloy-dyn-abi = "=0.8.3"
alloy-primitives = { version = "=0.8.3", default-features = false }
alloy-rlp = "=0.3.4"
alloy-sol-types = "=0.8.3"
alloy-trie = { version = "=0.5", default-features = false }
alloy-sol-macro = { version = "=0.8.3" }
alloy-consensus = { version = "=0.3.6", default-features = false }
alloy-eips = { version = "=0.3.6", default-features = false }
alloy-genesis = { version = "=0.3.6", default-features = false }
alloy-json-rpc = { version = "=0.3.6", default-features = false }
alloy-network = { version = "=0.3.6", default-features = false }
alloy-network-primitives = { version = "=0.3.6", default-features = false }
alloy-node-bindings = { version = "=0.3.6", default-features = false }
alloy-provider = { version = "=0.3.6", features = [
    "reqwest",
], default-features = false }
alloy-sol-macro-expander = { version = "=0.8.3" }
alloy-sol-macro-input = { version = "=0.8.3" }
alloy-pubsub = { version = "=0.3.6", default-features = false }
alloy-rpc-client = { version = "=0.3.6", default-features = false }
alloy-rpc-types = { version = "=0.3.6", features = [
    "eth",
], default-features = false }
alloy-sol-type-parser = { version = "=0.8.3" }
alloy-rpc-types-admin = { version = "=0.3.6", default-features = false }
alloy-rpc-types-anvil = { version = "=0.3.6", default-features = false }
alloy-rpc-types-beacon = { version = "=0.3.6", default-features = false }
alloy-rpc-types-debug = { version = "=0.3.6", default-features = false }
alloy-rpc-types-engine = { version = "=0.3.6", default-features = false }
alloy-rpc-types-eth = { version = "=0.3.6", default-features = false }
alloy-rpc-types-mev = { version = "=0.3.6", default-features = false }
alloy-rpc-types-trace = { version = "=0.3.6", default-features = false }
alloy-rpc-types-txpool = { version = "=0.3.6", default-features = false }
alloy-serde = { version = "=0.3.6", default-features = false }
alloy-signer = { version = "=0.3.6", default-features = false }
alloy-signer-local = { version = "=0.3.6", default-features = false }
alloy-transport = { version = "=0.3.6" }
alloy-transport-http = { version = "=0.3.6", features = [
    "reqwest-rustls-tls",
], default-features = false }
alloy-transport-ipc = { version = "=0.3.6", default-features = false }
alloy-transport-ws = { version = "=0.3.6", default-features = false }

# op
op-alloy-rpc-types = "0.2.12"
op-alloy-rpc-types-engine = "0.2.12"
op-alloy-network = "0.2.12"
op-alloy-consensus = "0.2.12"
serde = { version = "1.0.128", features = ["derive"] }
web3 = "0.19.0"
reth = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.7", optional = true }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", package = "reth-node-builder", tag = "v1.0.7", optional = true }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", package = "reth-node-ethereum", tag = "v1.0.7", optional = true }
reth-node-core = { git = "https://github.com/paradigmxyz/reth", package = "reth-node-core", tag = "v1.0.7", optional = true }
reth-provider = { git = "https://github.com/paradigmxyz/reth", package = "reth-provider", tag = "v1.0.7", optional = true }
reth-db = { git = "https://github.com/paradigmxyz/reth", package = "reth-db", tag = "v1.0.7", optional = true }
reth-tasks = { git = "https://github.com/paradigmxyz/reth", package = "reth-tasks", tag = "v1.0.7", optional = true }
reth-cli-runner = { git = "https://github.com/paradigmxyz/reth", package = "reth-cli-runner", tag = "v1.0.7", optional = true }
reth-cli = { git = "https://github.com/paradigmxyz/reth", package = "reth-cli", tag = "v1.0.7", optional = true }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth", package = "reth-cli-util", tag = "v1.0.7", optional = true }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", package = "reth-chainspec", tag = "v1.0.7", optional = true }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", package = "reth-tracing", tag = "v1.0.7", optional = true }
reth-auto-seal-consensus = { git = "https://github.com/paradigmxyz/reth", package = "reth-auto-seal-consensus", tag = "v1.0.7", optional = true }
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", package = "reth-basic-payload-builder", tag = "v1.0.7", optional = true }
reth-beacon-consensus = { git = "https://github.com/paradigmxyz/reth", package = "reth-beacon-consensus", tag = "v1.0.7", optional = true }
reth-ethereum-engine-primitives = { git = "https://github.com/paradigmxyz/reth", package = "reth-ethereum-engine-primitives", tag = "v1.0.7", optional = true }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", package = "reth-evm-ethereum", tag = "v1.0.7", optional = true }
reth-network = { git = "https://github.com/paradigmxyz/reth", package = "reth-network", tag = "v1.0.7", optional = true }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", package = "reth-node-api", tag = "v1.0.7", optional = true }
reth-payload-builder = { git = "https://github.com/paradigmxyz/reth", package = "reth-payload-builder", tag = "v1.0.7", optional = true }
reth-rpc = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc", tag = "v1.0.7", optional = true }
reth-rpc-api = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc-api", tag = "v1.0.7", features = ["client"], optional = true }
reth-rpc-types = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc-types", tag = "v1.0.7", optional = true}
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", package = "reth-transaction-pool", tag = "v1.0.7", optional = true }
reth-consensus = { git = "https://github.com/paradigmxyz/reth", package = "reth-consensus", tag = "v1.0.7", optional = true }
reth-ethereum-payload-builder = { git = "https://github.com/paradigmxyz/reth", package = "reth-ethereum-payload-builder", tag = "v1.0.7", optional = true }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", package = "reth-primitives", tag = "v1.0.7", optional = true }
reth-cli-commands = { git = "https://github.com/paradigmxyz/reth", package = "reth-cli-commands", features = ["dev"], tag = "v1.0.7", optional = true }

greth = { git = "https://github.com/Galxe/grevm-reth", package = "reth", branch = "v1.0.7-gravity", optional = true }
greth-node-builder = { git = "https://github.com/Galxe/grevm-reth", package = "reth-node-builder", branch = "v1.0.7-gravity", optional = true }
greth-node-ethereum = { git = "https://github.com/Galxe/grevm-reth", package = "reth-node-ethereum", branch = "v1.0.7-gravity", optional = true }
greth-node-core = { git = "https://github.com/Galxe/grevm-reth", package = "reth-node-core", branch = "v1.0.7-gravity", optional = true }
greth-provider = { git = "https://github.com/Galxe/grevm-reth", package = "reth-provider", branch = "v1.0.7-gravity", optional = true }
greth-db = { git = "https://github.com/Galxe/grevm-reth", package = "reth-db", branch = "v1.0.7-gravity", optional = true }
greth-tasks = { git = "https://github.com/Galxe/grevm-reth", package = "reth-tasks", branch = "v1.0.7-gravity", optional = true }
greth-cli-runner = { git = "https://github.com/Galxe/grevm-reth", package = "reth-cli-runner", branch = "v1.0.7-gravity", optional = true }
greth-cli = { git = "https://github.com/Galxe/grevm-reth", package = "reth-cli", branch = "v1.0.7-gravity", optional = true }
greth-cli-util = { git = "https://github.com/Galxe/grevm-reth", package = "reth-cli-util", branch = "v1.0.7-gravity", optional = true }
greth-chainspec = { git = "https://github.com/Galxe/grevm-reth", package = "reth-chainspec", branch = "v1.0.7-gravity", optional = true }
greth-tracing = { git = "https://github.com/Galxe/grevm-reth", package = "reth-tracing", branch = "v1.0.7-gravity", optional = true }
greth-auto-seal-consensus = { git = "https://github.com/Galxe/grevm-reth", package = "reth-auto-seal-consensus", branch = "v1.0.7-gravity", optional = true }
greth-basic-payload-builder = { git = "https://github.com/Galxe/grevm-reth", package = "reth-basic-payload-builder", branch = "v1.0.7-gravity", optional = true }
greth-beacon-consensus = { git = "https://github.com/Galxe/grevm-reth", package = "reth-beacon-consensus", branch = "v1.0.7-gravity", optional = true }
greth-ethereum-engine-primitives = { git = "https://github.com/Galxe/grevm-reth", package = "reth-ethereum-engine-primitives", branch = "v1.0.7-gravity", optional = true }
greth-evm-ethereum = { git = "https://github.com/Galxe/grevm-reth", package = "reth-evm-ethereum", branch = "v1.0.7-gravity", optional = true }
greth-network = { git = "https://github.com/Galxe/grevm-reth", package = "reth-network", branch = "v1.0.7-gravity", optional = true }
greth-node-api = { git = "https://github.com/Galxe/grevm-reth", package = "reth-node-api", branch = "v1.0.7-gravity", optional = true }
greth-payload-builder = { git = "https://github.com/Galxe/grevm-reth", package = "reth-payload-builder", branch = "v1.0.7-gravity", optional = true }
greth-rpc = { git = "https://github.com/Galxe/grevm-reth", package = "reth-rpc", branch = "v1.0.7-gravity", optional = true }
greth-rpc-api = { git = "https://github.com/Galxe/grevm-reth", package = "reth-rpc-api", branch = "v1.0.7-gravity", optional = true, features = ["client"] }
greth-rpc-types = { git = "https://github.com/Galxe/grevm-reth", package = "reth-rpc-types", branch = "v1.0.7-gravity", optional = true}
greth-transaction-pool = { git = "https://github.com/Galxe/grevm-reth", package = "reth-transaction-pool", branch = "v1.0.7-gravity", optional = true }
greth-consensus = { git = "https://github.com/Galxe/grevm-reth", package = "reth-consensus", branch = "v1.0.7-gravity", optional = true }
greth-ethereum-payload-builder = { git = "https://github.com/Galxe/grevm-reth", package = "reth-ethereum-payload-builder", branch = "v1.0.7-gravity", optional = true }
greth-primitives = { git = "https://github.com/Galxe/grevm-reth", package = "reth-primitives", branch = "v1.0.7-gravity", optional = true }
greth-cli-commands = { git = "https://github.com/Galxe/grevm-reth", package = "reth-cli-commands", features = ["dev"], branch = "v1.0.7-gravity", optional = true }
reqwest = "0.12.9"

[features]
preth = ["reth", "reth-node-builder", "reth-node-ethereum", "reth-node-core", "reth-provider", "reth-db", "reth-tasks", "reth-cli-runner", "reth-cli", "reth-cli-util", "reth-chainspec", "reth-tracing", "reth-auto-seal-consensus", "reth-basic-payload-builder", "reth-beacon-consensus", "reth-ethereum-engine-primitives", "reth-evm-ethereum", "reth-network", "reth-node-api", "reth-payload-builder", "reth-rpc", "reth-rpc-api", "reth-rpc-types", "reth-transaction-pool", "reth-consensus", "reth-ethereum-payload-builder", "reth-primitives", "reth-cli-commands"]
grevm = ["greth", "greth-node-builder", "greth-node-ethereum", "greth-node-core", "greth-provider", "greth-db", "greth-tasks", "greth-cli-runner", "greth-cli", "greth-cli-util", "greth-chainspec", "greth-tracing", "greth-auto-seal-consensus", "greth-basic-payload-builder", "greth-beacon-consensus", "greth-ethereum-engine-primitives", "greth-evm-ethereum", "greth-network", "greth-node-api", "greth-payload-builder", "greth-rpc", "greth-rpc-api", "greth-rpc-types", "greth-transaction-pool", "greth-consensus", "greth-ethereum-payload-builder", "greth-primitives", "greth-cli-commands"]
default = ["preth"]