base:
  role: "validator"
  data_dir: "/gravity_node/data"
  waypoint:
    from_file: "/gravity_node/config/waypoint.txt"

consensus:
  safety_rules:
    backend:
      type: "on_disk_storage"
      path: /gravity_node/data/secure_storage.json
    initial_safety_rules_config:
      from_file:
        waypoint:
          from_file: /gravity_node/config/waypoint.txt
        identity_blob_path: /gravity_node/config/identity.yaml
  enable_pipeline: true
  max_sending_block_txns_after_filtering: 15000
  max_sending_block_txns: 15000
  max_receiving_block_txns: 15000
  max_sending_block_bytes: 31457280 
  max_receiving_block_bytes: 31457280 
  quorum_store:
    receiver_max_total_txns: 7000
    sender_max_total_txns: 7000
    receiver_max_batch_bytes: 1048736 
    sender_max_batch_bytes: 1048736 
    sender_max_total_bytes: 1073741824 
    receiver_max_total_bytes: 1073741824 
    memory_quota: 1073741824 # 1GB
    db_quota: 1073741824 # 1GB
    back_pressure:
      dynamic_max_txn_per_s: 30000
      backlog_txn_limit_count: 50000
      backlog_per_validator_batch_limit_count: 2000

validator_network:
  network_id: validator
  listen_address: "/ip4/127.0.0.1/tcp/2024"
  discovery_method: 
    file:
      path: "/gravity_node/discovery"
      interval_secs: 3600
  mutual_authentication: true
  identity:
    type: "from_file"
    path: /gravity_node/config/identity.yaml

storage:
  dir: "/gravity_node/data"

node_config_path: "/gravity_node/config/nodes_config.json"

log_file_path: "/gravity_node/consensus_log"

inspection_service:
  port: 10000
  address: 0.0.0.0

mempool:
  capacity_per_user: 20000
