# - name: Check if cargo is available
#   shell: |
#     which cargo
#   register: cargo_check

# - debug:
#     var: cargo_check.stdout

- name: Debug cargo
  hosts: reth_servers
  tasks:
    - name: Check if cargo is available
      shell: |
        bash test.sh
      args:
        chdir: "/home/jingyue/projects/gravity-sdk"
      register: cargo_check
      become: true
      become_user: jingyue
      become_flags: '-l'
    
    - name: Display cargo check output
      debug:
        var: cargo_check.stdout

    
    # - debug:
    # var: cargo_check.stdout