---
- name: Start Reth service
  hosts: reth_servers
  tasks:
    - name: Start Reth service using script
      shell: |
        {{ reth_env }} bash start.sh
      args:
        chdir: "/tmp/{{ reth_node_id }}/script"
      async: 30
      poll: 5
      register: deploy_service_log

    - name: Display service start logs
      debug:
        var: deploy_service_log
