---
- name: Start Reth service
  hosts: reth_servers
  tasks:
    - name: Start Reth service using script
      shell: |
        {{ reth_env }} bash start.sh --node {{ reth_node_id }}
      args:
        chdir: "/tmp/{{ reth_node_id }}/script"
      async: 30
      poll: 5
      register: deploy_service_log

    - name: Append service start logs to collection
      set_fact:
        log_collection: "{{ log_collection + [deploy_service_log] }}"
