- name: Stop all Reth instances
  hosts: reth_servers
  tasks:
    - name: Stop Reth service using script
      shell: |
        bash stop.sh
      args:
        chdir: "/tmp/{{ reth_node_id }}/script"