- name: Stop all Reth instances
  hosts: reth_servers
  vars:
    log_collection: []
  tasks:
    - name: Stop Reth service using script
      shell: |
        bash stop.sh
      args:
        chdir: "{{ reth_install_dir }}/{{ reth_node_id }}/script"
      register: stop_log
    
    - name: Append stop logs to collection
      set_fact:
        log_collection: "{{ log_collection + [stop_log] }}"
    
    - name: Output collected logs
      debug:
        msg: "{{ item.stdout | default('') }}"
      with_items: "{{ log_collection }}"