- name: Deploy and start Reth on servers
  hosts: reth_servers
  vars:
    log_collection: []
  tasks:
    - name: Pull and checkout code
      shell: |
        git checkout main && git pull && git checkout {{ tag_or_brach }}
      async: 600
      poll: 30
      args:
        chdir: "{{ reth_root_dir }}"
      register: git_log
    - name: Append git logs to collection
      set_fact:
        log_collection: "{{ log_collection + [git_log] }}"

    - name: Compile Reth with custom options
      shell: |
        bash -c ". "$HOME/.cargo/env" && make {{ reth_compile_options }}"
      async: 1200
      poll: 30
      args:
        chdir: "{{ reth_root_dir }}"
      register: compile_log
    - name: Append compile logs to collection
      set_fact:
        log_collection: "{{ log_collection + [compile_log] }}"

    - name: Deploy Reth service using script
      shell: |
        bash deploy_utils/deploy.sh {{ reth_node_arg }}
      async: 120
      poll: 5
      args:
        chdir: "{{ reth_root_dir }}"
      register: deploy_service_log
    - name: Append service start logs to collection
      set_fact:
        log_collection: "{{ log_collection + [deploy_service_log] }}"

    - name: Copy nodes config to remote
      copy:
        src: ./server_confs/nodes_config.json
        dest: "/tmp/{{ reth_node_id }}/genesis/nodes_config.json"

    - name: Copy nodes discover to remote
      copy:
        src: ./server_confs/discovery
        dest: "/tmp/{{ reth_node_id }}/discovery"

    - name: Synchronize genesis directory to remote, overwrite existing directory
      synchronize:
        src: "./server_confs/{{ reth_node_id }}/genesis/"
        dest: "/tmp/{{ reth_node_id }}/genesis/"
        recursive: yes
        delete: yes

    - name: Copy start bash to remote
      copy:
        src: "{{ reth_root_dir }}/deploy_utils/start.sh"
        dest: "/tmp/{{ reth_node_id }}/script"

    - name: Output collected logs
      debug:
        msg: "{{ item.stdout | default('') }}"
      with_items: "{{ log_collection }}"
