# Four-validator live Binance price-feed integration test.

[cluster]
name = "gravity-devnet-binance-price-feed-multivalidator"
base_dir = "/tmp/gravity-cluster-binance-price-feed-multivalidator"

[genesis_source]
genesis_path = "./artifacts/genesis.json"
waypoint_path = "./artifacts/waypoint.txt"

[[nodes]]
id = "node1"
role = "genesis"
source = { project_path = "../" }
host = "127.0.0.1"
validator_port = 46380
vfn_port = 46390
rpc_port = 49755
api_port = 49280
metrics_port = 50203
inspection_port = 41102
https_port = 42124
authrpc_port = 49775
reth_p2p_port = 53226

[[nodes]]
id = "node2"
role = "genesis"
source = { project_path = "../" }
host = "127.0.0.1"
validator_port = 46381
vfn_port = 46391
rpc_port = 49756
api_port = 49281
metrics_port = 50204
inspection_port = 41103
https_port = 42125
authrpc_port = 49776
reth_p2p_port = 53227

[[nodes]]
id = "node3"
role = "genesis"
source = { project_path = "../" }
host = "127.0.0.1"
validator_port = 46382
vfn_port = 46392
rpc_port = 49757
api_port = 49282
metrics_port = 50205
inspection_port = 41104
https_port = 42126
authrpc_port = 49777
reth_p2p_port = 53228

[[nodes]]
id = "node4"
role = "genesis"
source = { project_path = "../" }
host = "127.0.0.1"
validator_port = 46383
vfn_port = 46393
rpc_port = 49758
api_port = 49283
metrics_port = 50206
inspection_port = 41105
https_port = 42127
authrpc_port = 49778
reth_p2p_port = 53229

[faucet_init]
num_accounts = 0
